version: 2.1

commands:
  swiftlint:
    steps:
      - run: mkdir -p build/reports/
      - run: swiftlint lint --strict --reporter junit > build/reports/junit.xml
      - store_test_results:
          path: build/reports/

jobs:
  build_with_image:
    parameters:
      image:
        type: string
    docker:
      - image: << parameters.image >>
    steps:
      - checkout
      - run: apt-get update && apt-get install -y libunwind8
      - run: swift test

workflows:
  workflow:
    jobs:
      - build_with_image:
          name: swift-5.0-branch
          image: norionomura/swift:swift-5.0-branch
      - build_with_image:
          name: swift-nightly
          image: norionomura/swift:nightly
