name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: GitHub Action for SwiftLint
      uses: norio-nomura/action-swiftlint@use-event-payload
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
