name: Nightly

on:
  push:
    branches: [master]
    paths: 
      - '.github/workflows/nightly.yml'
      - 'Package*'
      - 'Sources/**'
      - 'Tests/**'
  schedule:
    - cron: '0 4 * * *'

jobs:
  Nightly:
    runs-on: ubuntu-latest
    container:
      image: norionomura/swift:nightly
    steps:
      - run: uname -a
      - run: apt-get update && apt-get install -y libunwind8
      - uses: actions/checkout@v1
      - run: swift test --parallel
